services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.4
    container_name: kibana
    restart: always
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=7c16804a48f31d1cf9f112f08cd3201c

networks:
  elastic:
    external: true
