services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.4
    container_name: kibana
    restart: always
    #depends_on:
    #  - elasticsearch
    #volumes:
    #  - kibana_data:/usr/share/kibana/data
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=ssamplekey123456
      # - XPACK_SECURITY_ENABLE=true
networks:
  elastic:
    external: true
#volumes:
#  kibana_data:
#    driver: local