version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1@
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres/data
volumes:
  db: 
    driver: local
