services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.4
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      #- ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      #- ELASTICSEARCH_USERNAME=elastic
      #- ELASTICSEARCH_PASSWORD=changeme
      #- bootstrap.memory_lock=true
      #- xpack.security.enabled=true
      #- xpack.security.http.ssl.enabled=true
      #- xpack.security.transport.ssl.enabled=true
    ports:
      - "9200:9200"
    networks:
      - elastic
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
networks:
  elastic:
    external: true
volumes:
  elastic_data:
    driver: local