apm-server:
  host: "0.0.0.0:8200"
  auth:
    secret_token: "changemechangemechangeme"
  rum:
    enabled: true
  kibana:
    enabled: true
    host: "http://kibana:5601"
    username: elastic
    password: changeme
  ssl:
    enabled: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme

logging.level: debug