services:
  apm_server:
    image: docker.elastic.co/apm/apm-server:8.19.4
    container_name: apm_server
    restart: always
    networks:
      - elastic
    ports:
      - "8200:8200"
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro

networks:
  elastic:
    external: true
