version: '3.8'
services:
  db:
    image: mvertes/alpine-mongo:latest
    restart: always
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=Password2
    ports:
     - '27017:27017'
    volumes:
      - db:/data/db
volumes:
  db: 
    driver: local
