version: '3.8'
services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "Password@2"
      MYSQL_ROOT_PASSWORD: "Password@2"
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init-dump:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
