services:
  mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    networks:
      - defaults
    environment:
      MYSQL_USER: "mysqluser"
      MYSQL_PASSWORD: "Password@2"
      MYSQL_ROOT_PASSWORD: "Password@2"
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./init-dump:/docker-entrypoint-initdb.d
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 60s
    #   timeout: 5s
    #   retries: 5

volumes: {}

networks:
  defaults:
    external: true