version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes: 
      - db:/data
volumes:
  db: 
    driver: local
