services:
  cache:
    container_name: "redis"
    image: redis:7.0-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=mysecretpassword # Set a password for Redis (adjust as needed)
    ports:
      - "6379:6379"
    command: redis-server --loglevel notice # Less verbose logging level
    volumes:
      - data:/data
volumes:
  data:
    driver: local
